spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
      bindings:
        orderSupplier-out-0:
          destination: order-event
          contentType: application/json
        paymentEventConsumer-in-0 :
          destination: payment-event
          contentType: application/json
server:
  port: 8081